[package]
name = "sokoban"
description = "Entity Component System'i tanıyoruz"
authors = ["Burak Selim Şenyurt"]
version = "0.1.0"
edition = "2021"

[dependencies]
ggez="0.7.0"
glam = { version = "0.20.5", features = ["mint"] }
specs={version="0.17.0", features=["specs-derive"]}