[package]
name = "actix_views"
description = "A new project about using the views with Actix Framework."
authors = ["Burak Selim Senyurt<selim@buraksenyurt.com>"]
version = "0.1.0"
edition = "2021"

[dependencies]
actix-web="4.0.1"
actix-rt="2.7.0"
