[package]
name = "only_you"
description = "Arc, Mutex nasıl kullanılır ve işler crossbeam ile nasıl daha güzelleşir ona bakıyorum."
version = "0.1.0"
edition = "2021"

[dependencies]
crossbeam="0.8.1"
parking_lot = "0.12.0"