[package]
name = "imager"
version = "0.1.0"
edition = "2021"

[lib]
name="imagix"
path="src/imagix/mod.rs"

[[bin]]
name="imager"
path="src/imager.rs"

[dependencies]
image="0.24.1"
structopt = "0.3.26"
